graph TD
    A[Start: _performNavigation<br>with pathname] --> B{Is this the current navigation?}
    B -- No --> C[End: navigation has been completed]
    B -- Yes --> D{Is skipLeaveCallbacks true?}
    
    D -- No --> E(await _currentRoute.leave)
    E --> F{Does callback ‘leave’ return false?}
    F -- Yes --> C
    F -- No --> G(await _checkChildrenCanLeave)
    G --> H{Can children leave?}
    H -- No --> C
    H -- Yes --> I{Is this the current navigation?}
    I -- No --> C
    I -- Yes --> J(Continue)
    
    D -- Yes --> J
    
    J --> K("_getRoute(pathname)")
    K --> L{Was a route found?}
    
    L -- No --> M(Throw Error: No route found)
    L -- Yes --> N(Get `tailGroup` from route)
    N --> O{Does ‘enter’ callback exist?}
    
    O -- Yes --> P(await route.enter)
    P --> Q{Does callback ‘enter’ return false?}
    Q -- Yes --> C
    Q -- No --> R(Update controller state)
    
    O -- No --> R
    
    R --> S{Is this the current navigation?}
    S -- No --> C
    S -- Yes --> T{Does the current route end with ‘*’}
    
    T -- Yes --> U(Propagate navigation<br>with `tailGroup` to children)
    T -- Yes --> V(await Promise.all<br>child._gotoInternal)
    V --> W{Is this the current navigation?}
    W -- No --> C
    W -- Yes --> X(requestUpdate)
    
    T -- No --> X
    
    X --> Y(Trigger ‘lit-router-location-changed’ event)
    Y --> Z[End of Navigation]
        
    style C fill:#f9d7d7,stroke:#c00,stroke-width:2px,color:#3e3e3e
    style M fill:#f9d7d7,stroke:#c00,stroke-width:2px,color:#3e3e3e
    style Z fill:#d4edda,stroke:#155724,stroke-width:2px