graph TD
    A[Start: Router instance] --> B(constructor)
    B --> C(hostConnected)
    C --> D{Is it a root router?}
    D -- Yes --> E(Add click/popstate listeners to window)
    D -- Yes --> F(Call _safeNavigate)
    F --> G(Call goto<br>with current URL)
    
    H[Click Navigation] --> I(onClick)
    I --> J{Is it a valid internal link?}
    J -- Yes --> K(e.preventDefault)
    K --> L(Call _safeNavigate)
    L --> M(Call goto<br>with link URL)
    
    N[History Navigation] --> O(onPopState)
    O --> P(Call _safeNavigate)
    P --> Q(Call goto<br>with history URL)
    
    R[goto method] --> S(Call _safeNavigate)
    S --> T(Call _gotoInternal<br>from RoutesController)
    T --> U{Was _gotoInternal<br>navigation successful?}
    U -- Yes --> V{Is it browser navigation or nested navigation?}
    V -- No --> W(window.history.pushState)
    V -- Yes --> X(Do not refresh history)

    U -- No --> Y(Revert URL if it was refreshed)
    
    Z[_safeNavigate method] --> ZA(try/catch)
    ZA -- Success --> ZB(Return)
    ZA -- Error --> ZC(console.warn)
    ZC --> ZD(Call _gotoRecover)
    ZD --> ZE(End with possible recovery)
    
    style CC fill:#d4edda,stroke:#155724,stroke-width:2px
    style BB fill:#f9d7d7,stroke:#c00,stroke-width:2px